### ISSUE TITLE
where are the services for specific game

### ISSUE THREAD

**Issue by Gusabary** [SailGame/proto#2]
in `uno.proto` there are only some messages type defined. I have not found where services are, e.g.
```protobuf
rpc Draw(DrawArgs) returns (DrawRet) {}
```

are those not defined yet? or anything else I misunderstood

**Comment by Veiasai** [comment]
not defined.

You could use whatever you like.
but currently,  you should only have 3 types:
1. StartGameSettings
2. UserOperation
3. NotifyMsg

1 used in core/provider.proto/StartGameArgs/custom
2 used in core/provider.proto/UserOperationArgs/custom
3 used in core/provider.proto/NotifyMsg/custom

the game client fill 1&2, and handle 3.
your game provider should handle 1&2, and publish 3.
